import React, { useEffect } from 'react';
import { NextPage } from 'next';
import Head from 'next/head';
import styles from 'styles/Home.module.scss';
import Test from '@components/Test';

const Home: NextPage = () => {
  useEffect(() => {
    const { Elm } = require('~/elm/Main');
    const app = Elm.Main.init({ node: document.getElementById('elm-node') });
  }, []);
  return (
    <div className={styles.container}>
      <Test />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

export default Home;
